#!/usr/bin/env bash
# Generated by bin/inject. Do not edit manually.
# Policy: block-destructive-shell
# Source: packages/cli/library/kiro/hooks/block-destructive-shell.sh

if ! command -v python3 >/dev/null 2>&1; then
  echo '{"decision": "deny", "reason": "Python3 is required but not found"}'
  exit 2
fi
input="$(cat)"

JSON_INPUT="$input" python3 - <<'PY'
import json, os, sys
try:
    data = json.loads(os.environ.get("JSON_INPUT", ""))
except Exception:
    print(json.dumps({"decision": "deny", "reason": "Failed to parse JSON input"}))
    sys.exit(2)

tool_name = data.get("toolName") or data.get("tool_name")
if tool_name not in ("shell", "run_shell_command", "run_shell", "Bash", "bash"):
    print(json.dumps({"decision": "allow"}))
    sys.exit(0)

tool_input = data.get("toolInput") or data.get("tool_input")
command = None
if isinstance(tool_input, dict):
    command = tool_input.get("command")
elif isinstance(tool_input, str):
    command = tool_input
else:
    command = data.get("command")

if not isinstance(command, str):
    print(json.dumps({"decision": "deny", "reason": "No command string found"}))
    sys.exit(2)

command = command.strip()
denied_prefixes = ['rm -rf /', 'rm -rf /*', 'mkfs', 'dd if=/dev/zero of=', 'dd if=/dev/zero of=/dev/', '> /dev/sd', 'shutdown', 'poweroff', 'reboot', 'halt']
if any(command == p or command.startswith(p + " ") for p in denied_prefixes):
    print(json.dumps({"decision": "deny", "reason": "Destructive shell command blocked by lazyai policy"}))
    sys.exit(2)

print(json.dumps({"decision": "allow"}))
sys.exit(0)
PY