#!/usr/bin/env bash
# Generated by bin/inject. Do not edit manually.
# Policy hash: 652d228a03e20ea7db0bb1f8278d2037689d17d882f265692b0f7837e117bd11

if ! command -v python3 >/dev/null 2>&1; then
  exit 2
fi
input="$(cat)"

JSON_INPUT="$input" python3 - <<'PY'
import json, os, sys
try:
    data = json.loads(os.environ.get("JSON_INPUT", ""))
except Exception:
    sys.exit(2)

tool_name = data.get("toolName") or data.get("tool_name")
if tool_name not in ("bash", "Bash"):
    sys.exit(0)

tool_input = data.get("toolInput") or data.get("tool_input")
command = None
if isinstance(tool_input, dict):
    command = tool_input.get("command")
elif isinstance(tool_input, str):
    command = tool_input
else:
    command = data.get("command")

if not isinstance(command, str):
    sys.exit(2)

command = command.strip()
denied_prefixes = ['rm -rf /', 'rm -rf /*', 'mkfs', 'dd if=/dev/zero of=', 'dd if=/dev/zero of=/dev/', '> /dev/sd', 'shutdown', 'poweroff', 'reboot', 'halt']
if any(command == p or command.startswith(p + " ") for p in denied_prefixes):
    print("Destructive shell command blocked by lazyai policy", file=sys.stderr)
    sys.exit(2)
sys.exit(0)
PY