#!/usr/bin/env bash
# Generated by bin/inject. Do not edit manually.
# Policy hash: 76e156b07c293ac503daa48490009249065851143d897394f8f9a2e27be15ca9
# Advisory policy hook for caveman-memory-promotion. No runtime block is configured yet.
exit 0