#!/usr/bin/env bash
# Generated by bin/inject. Do not edit manually.
# Policy hash: 1e2d432ad97cd9179e165e159061564df833ca51def01742fa3915c40f7abd52
REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
"$REPO_ROOT/bin/startup-self-heal" --cli copilot --event session-start --quiet || true