name: DCO Check

on:
  pull_request:
    branches: [main]

jobs:
  dco:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Check DCO sign-off
        uses: christophebedard/dco-check@ec8bfc43106afe98b323ace9133650df10497e12 # v0.5.1
        with:
          args: --verbose --exclude-pattern dependabot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
